spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
jwt:
  secret: my-secret-key
  expiration: 3600000
